import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { api } from "../utils/api";

const protectedLogin: NextPage = () => {
    const hello = api.example.hello.useQuery({ text: "from tRPC" });
    const { data: session } = useSession();
  
    return (
      <>
        <Head>
          <title>OpenFuel </title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-neutral-800 to-neutral-900">
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
              Open<span className="text-amber-600">Fuel</span>
            </h1>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
              <Link
                className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                href="/quote"
              >
                <h3 className="text-2xl font-bold">Quote →</h3>
                <div className="text-lg">
                  Get a Quote for all Fuel Services we offer, as many times as you want!
                </div>
              </Link>
              <Link
                className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                href="profile"
              >
                <h3 className="text-2xl font-bold">Profile →</h3>
                <div className="text-lg">
                  Manage your Profile Information - Name, Address, City, State, and Zip Code.
                </div>
              </Link>
            </div>

            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
              <Link
                className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                href="/history"
              >
                <h3 className="text-2xl font-bold">History →</h3>
                <div className="text-lg">
                  Navigate along all your previous quote history, so you don't forget your last purchases ;)
                </div>
              </Link>
              <Link
                className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                href="/"
              >
                <h3 className="text-2xl font-bold">Sign Out →</h3>
                <div className="text-lg">
                  We appreciate your Business and we hope that you have an amazing day ahead! :)
                </div>
              </Link>
            </div>
            {/* TRPC Stuff: */}
            {/* <div className="flex flex-col items-center gap-2">
              <p className="text-2xl text-white">
                {hello.data ? hello.data.greeting : "Loading tRPC query..."}
              </p>
              <AuthShowcase />
            </div> */}
          </div>
        </main>
  
        {/* <footer className="py-4 px-8 text-center">
          <p>&copy; 2023 OpenFuel. All rights reserved.</p>
        </footer> */}
      </>
    );
  };
  
  export default protectedLogin;
  
  // const AuthShowcase: React.FC = () => {
  //   const { data: sessionData } = useSession();
  
  //   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
  //     undefined, // no input
  //     { enabled: sessionData?.user !== undefined }
  //   );
  
  //   return (
  //     <div className="flex flex-col items-center justify-center gap-4">
  //       <p className="text-center text-2xl text-white">
  //         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
  //         {secretMessage && <span> - {secretMessage}</span>}
  //       </p>
  //       <button
  //         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
  //         onClick={sessionData ? () => void signOut() : () => void signIn()}
  //       >
  //         {sessionData ? "Sign out" : "Sign in"}
  //       </button>
  //     </div>
  //   );
  // };
  